services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news-aggregator-app
    container_name: news_aggregator_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    command: |
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && \
             chmod -R 775 /var/www/storage /var/www/bootstrap/cache && \
             php-fpm -F"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

#   scheduler:
#     image: news-aggregator-app
#     container_name: news_aggregator_scheduler
#     restart: unless-stopped
#     volumes:
#       - .:/var/www
#     networks:
#       - laravel
#     depends_on:
#       - app
#       - mysql
#     command: php artisan schedule:work
#     deploy:
#       resources:
#         limits:
#           cpus: '0.25'
#           memory: 256M
#         reservations:
#           cpus: '0.1'
#           memory: 128M

  mysql:
    image: mysql:5.7
    container_name: news_aggregator_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    image: nginx:alpine
    container_name: news_aggregator_nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'  # Access phpMyAdmin at http://localhost:8081
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  laravel:
    driver: bridge

volumes:
  mysql-data:
    driver: local
